version: '3.4'

services:
  bankmergecotask3:
    image: bankmergecotask3
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
